blog/models.py
from flask_login import UserMixin

from blog.app import db


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))

blog/app.py
from flask import Flask, redirect, url_for
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

login_manager = LoginManager()


def create_app() -> Flask:
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '97rvg1t2+jd#i%wz(fz%yn-#27a#hb&aq5+)a@+n(8_$zz2=31'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

    db.init_app(app)

    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        User.query.get(int(user_id))


    from .models import User

    register_blueprints(app)
    return app


def register_blueprints(app) -> Flask:
    from blog.user.views import user
    from blog.report.views import report
    from blog.auth.views import auth

    app.register_blueprint(user)
    app.register_blueprint(report)
    app.register_blueprint(auth)

blog/report/views.py
from flask import Blueprint, render_template

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static')


@report.route('/')
def report_list():
    return render_template(
        'reports/list.html',
        reports=[1, 2, 3, 4, 5]
        )

blog/user/views.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required
from werkzeug.exceptions import NotFound


user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('/')
def user_list():
    from blog.models import User
    users = User.query.all()
    return render_template(
        'users/list.html',
        users=users,
    )


@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    from blog.models import User
    user = User.query.filter_by(id=pk).one_or_none()
    if not user:
        raise NotFound(f'User #{pk} not found')
    return render_template(
        'users/profile.html',
        user=user,
    )

blog/views/users.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound


users_app = Blueprint("users_app", __name__)
USERS = {
    1: "James",
    2: "Brian",
    3: "Peter",
}


@users_app.route("/", endpoint="list")
def users_list():
    return render_template("user/list.html", users=USERS)


@users_app.route("/<int:user_id>/", endpoint="details")
def user_details(user_id: int):
    try:
        user_name = USERS[user_id]
    except KeyError:
        raise NotFound(f"User #{user_id} doesn't exist!")
    return render_template('user/profile.html', user_id=user_id, user_name=user_name)

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
  {% block body %} {% endblock %}
</div>

{% block js %}
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"> </script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
{% endblock %}
</body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.user_list')}}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('report.report_list')}}">Reports</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
                {% endif %}}
            </ul>
        </div>
    </div>
</nav>

blog/templates/reports/list.html
{% extends 'base.html' %}

{% block title %}Reports list {% endblock %}

{% block body %}
<div class="row">
    <div class="col">
          <h1>Reports::</h1>
    {% for report in reports %}
        <ul>
            <li>{{report}}</li>
        </ul>
    {% endfor %}
    </div>
  </div>

{% endblock %}}

blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
  User detail
{% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>



{% endblock %}}

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}Users list {% endblock %}

{% block body %}
<div class="row">
    <div class="col">
          <h1>Users:</h1>
    {% for user in users %}
        <ul>
            <li><a href="{{url_for('user.profile', pk=user.id) }}">{{user.email}}</a> </li>
        </ul>
    {% endfor %}
    </div>
  </div>

{% endblock %}}

blog/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
  User detail
{% endblock %}

{% block body %}
    <h1>{{ user.email }}</h1>



{% endblock %}}